name: install,lint,prettier,jest,playwright,codecov

on:
  pull_request:
    branches:
      - "develop"
      - "main"

jobs:
  checkout-and-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

  install-dependencies:
    runs-on: ubuntu-latest
    needs: checkout-and-setup

    steps:
      - name: Install Node modules
        run: npm ci

  lint:
    runs-on: ubuntu-latest
    needs: install-dependencies

    steps:
      - name: Lint
        run: npm run lint

  prettier-check:
    runs-on: ubuntu-latest
    needs: install-dependencies

    steps:
      - name: Prettier
        run: npm run prettier:check

  jest:
    runs-on: ubuntu-latest
    needs: install-dependencies

    steps:
      - name: Jest
        run: npm run test

  code-coverage:
    runs-on: ubuntu-latest
    needs: jest

    steps:
      - name: Code Coverage
        run: npm run coverage && npm run report

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          name: Upload reports to codecov
          fail_ci_if_error: true
          verbose: true

  upload-codecov:
    runs-on: ubuntu-latest
    needs: code-coverage

    steps:
      - run: |
          set -e
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          find . -iregex "codecov.*"
          chmod +x codecov 
          ./codecov -t ${CODECOV_TOKEN}
          rm codecov

  build:
    runs-on: ubuntu-latest
    needs: install-dependencies

    steps:
      - name: Build Project
        run: npm run build
